language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.3
    - android-23
    - sys-img-armeabi-v7a-android-21
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

before_script:
  - chmod +x gradlew

script: ./gradlew connectedAndroidTest